### ISSUE TITLE
bioconda recipe for NLPPrecursor

### ISSUE THREAD

**Issue by nick-youngblut** [magarveylab/NLPPrecursor#1]
As stated in the README:

> Conda is highly recommended, create a new environment specifically for NLPPrecursor for the easiest build

conda helps provide easy install + management of dependencies for NLPPrecursor. For developers that would like to use NLPPrecursor as a dependency for their own software, it would be beneficial if NLPPrecursor is directly integrated into conda (eg., via a bioconda recipe). 

Are there any plans of creating a bioconda recipe for NLPPrecursor?

**Comment by nishanthmerwin** [comment]
Hi, thanks for looking into this repository. Currently, we have no plans to create a bioconda recipe for this repository.

I personally don't have any experience doing this, but would be happy to review a pull request and merge it into the main code base if you were to implement this in a branch / fork.
