### ISSUE TITLE
package directory protai does not exist

### ISSUE THREAD

**Issue by DasRheingold** [magarveylab/NLPPrecursor#2]
Hi,

I have been trying to reproduce the results by following the instructions. However, it seems in any way I tried to set up the nlpprecursor repo, I always encounter the issue of missing the protai directory and contents inside it. I am wondering if it is the issue with my installation or protai should have been part of the repo. 

Thank you!

**Comment by nishanthmerwin** [comment]
Hi,

Thanks for catching that. I removed all references to protai, it was just the old name for this repo before we decided to do some rebranding!
